
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "sqlite::@file(manifest/database/sqlite/DCIM.NEXT.db)"
        descriptionTag: true
        jsonCase: CamelLower

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app